---
baseURL: http://localhost:1313
languageCode: en-us
title: Liz Dahlstrom
theme: github.com/xianmin/hugo-theme-jane

module:
  imports:
    - path: "github.com/xianmin/hugo-theme-jane"
      disable: false
