
# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: false
  hl_Lines: ''
  hl_inline: false
  lineAnchors: ''
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: true
  noClasses: true
  style: 'friendly'
  tabWidth: 4

tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 1